version: 2.1
  jobs:
    test:
      docker:
        - image: circleci/python
      steps:
        - checkout
        - run: echo "done"

workflows:
  version: 2.1
    quick_test:
      jobs:
        - test:
